# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDdTZ_vVn39omnr85GBFUpGZ9yt3UNeV
"""

import numpy as np
import pandas as pd

def add_time_features(df, datetime_col='datetime'):
    """
    df: pandas DataFrame
    datetime_col: 날짜시간 컬럼 이름 (예: 'datetime', '일시' 등)
    """
    # 1) datetime 형식으로 변환
    df[datetime_col] = pd.to_datetime(df[datetime_col])
    dt = df[datetime_col]

    # 2) 월/일/시간, 연 기준 일자(day of year)
    df['month']     = dt.dt.month        # 1 ~ 12
    df['day']       = dt.dt.day          # 1 ~ 28~31
    df['hour']      = dt.dt.hour         # 0 ~ 23
    df['dayofyear'] = dt.dt.dayofyear    # 1 ~ 365 또는 366
    df['weekday'] = dt.dt.weekday
    wd_col='풍향(16방위)'
    ws_col='풍속(m/s)'

    # 해당 연도가 윤년인지 여부 (True/False)
    is_leap = dt.dt.is_leap_year
    # 연도의 총 일수: 윤년이면 366, 아니면 365
    days_in_year = np.where(is_leap, 366, 365)
    # 해당 월의 총 일수 (28, 29, 30, 31 중 하나)
    days_in_month = dt.dt.days_in_month

    # 3) 월(month) 주기 인코딩 (12개월 주기)
    theta_month = 2 * np.pi * (df['month'] - 1) / 12.0
    df['month_sin'] = np.sin(theta_month)
    df['month_cos'] = np.cos(theta_month)

    # 4) 시간(hour) 주기 인코딩 (24시간 주기)
    theta_hour = 2 * np.pi * df['hour'] / 24.0
    df['hour_sin'] = np.sin(theta_hour)
    df['hour_cos'] = np.cos(theta_hour)

    # 5) 월 안의 날짜(day in month) 주기 인코딩
    theta_day = 2 * np.pi * (df['day'] - 1) / days_in_month
    df['day_sin'] = np.sin(theta_day)
    df['day_cos'] = np.cos(theta_day)

    # 6) 연 기준 일자(day of year) 주기 인코딩
    #    평년이면 365일, 윤년이면 366일을 주기로 사용
    theta_doy = 2 * np.pi * (df['dayofyear'] - 1) / days_in_year
    df['doy_sin'] = np.sin(theta_doy)
    df['doy_cos'] = np.cos(theta_doy)

    #    월=0, ..., 일=6 이라서 그대로 0~6 사용
    theta_wd = 2 * np.pi * df['weekday'] / 7.0
    df['weekday_sin'] = np.sin(theta_wd)
    df['weekday_cos'] = np.cos(theta_wd)

    #풍속변환
    theta = np.deg2rad(df[wd_col])
    # 성분 계산
    df['wind_x'] = df[ws_col] * np.sin(theta)
    df['wind_y'] = df[ws_col] * np.cos(theta)

    # 불필요한 임시 컬럼 삭제
    df.drop(columns=['month'], inplace=True)
    df.drop(columns=['day'], inplace=True)
    df.drop(columns=['hour'], inplace=True)
    df.drop(columns=['dayofyear'], inplace=True)
    df.drop(columns=['weekday'], inplace=True)

    return df

import pandas as pd

def add_lag_and_diff_features(df, cols):
    """
    df   : 시간 순서대로 정렬된 DataFrame
    cols : lag / 차이 / 이동평균을 만들 열 이름 리스트

    생성되는 것:
      - {col}_lag{lag}  : lag 값
      - {col}_diff{lag} : 현재 - lag 값
      - {col}_ma{w}     : w개 window 이동평균
    """
    # 1) 사용할 lag, window 정의
    lags = list(range(1, 25)) + [48, 72, 168]               # 1~24, 48, 72, 168
    windows = list(range(3, 25, 3)) + list(range(48, 169, 24))  # 3,6,...,24, 48,72,...,168

    # 2) 새로 만들 모든 컬럼을 여기다가 모은 뒤, 마지막에 한 번에 concat
    new_cols = {}

    # 2-1) lag & diff 컬럼
    for col in cols:
        for lag in lags:
            lag_col_name = f'{col}_lag{lag}'
            diff_col_name = f'{col}_diff{lag}'

            lag_series = df[col].shift(lag)           # 이전 값
            new_cols[lag_col_name] = lag_series       # lag 컬럼
            new_cols[diff_col_name] = df[col] - lag_series  # 현재 - 이전

    # 2-2) 이동평균 컬럼
    for col in cols:
        for w in windows:
            ma_col_name = f'{col}_ma{w}'   # ma = moving average
            new_cols[ma_col_name] = df[col].rolling(window=w, min_periods=w).mean()

    # 3) 새 컬럼들만 모은 DataFrame 만들고, 원본 df와 한 번에 결합
    new_df = pd.DataFrame(new_cols, index=df.index)
    df = pd.concat([df, new_df], axis=1)

    # 4) fragment 해소용 copy (선택이지만 경고 줄이기에 좋음)
    df = df.copy()

    return df

# 1) 원본 파일 읽기
df = pd.read_csv("/content/weather_data_with_feel.csv")

# 2) 시간 관련 피처 추가
df = add_time_features(df, datetime_col='datetime')  # datetime 컬럼 이름에 맞게 수정
#lag 관련 피처 추가
df = add_lag_and_diff_features(df, cols=('기온(°C)','상대습도(%)','풍속(m/s)','체감온도(°C)','wind_x', 'wind_y','heat_stress','cold_stress'))

# 3) 새로운 CSV 파일로 저장
output_path = "/content/청주_열공급량_기상변수_lag추가.csv"

df.to_csv(output_path, index=False, encoding='utf-8-sig')